package se.anders.tunerstudio.pidautotune.session;
import se.anders.tunerstudio.pidautotune.controller.DcIacSettingsAccess;
import se.anders.tunerstudio.pidautotune.live.*;
import se.anders.tunerstudio.pidautotune.recommendation.*;
import java.util.*;
/** Immutable archived summary of one manual DC-IAC tuning/capture iteration. */
public final class DcIacTuningSessionSummary {
 private final int sequence;private final String configurationName,dominantBiasStatus,dominantPidStatus;private final double p,i,d,centerTarget,targetSpan,medianBiasCorrectionAbs,medianOvershootAbs,medianSteadyErrorAbs,medianPeakDuty,medianInitialIAbs;private final int staticEvidenceCount,dynamicEvidenceCount,quantitativeCount,sourceLimitedCount;
 public DcIacTuningSessionSummary(int sequence,String configurationName,double p,double i,double d,int staticEvidenceCount,int dynamicEvidenceCount,int quantitativeCount,int sourceLimitedCount,double centerTarget,double targetSpan,double medianBiasCorrectionAbs,double medianOvershootAbs,double medianSteadyErrorAbs,double medianPeakDuty,double medianInitialIAbs,String dominantBiasStatus,String dominantPidStatus){this.sequence=sequence;this.configurationName=configurationName==null?"":configurationName;this.p=p;this.i=i;this.d=d;this.staticEvidenceCount=staticEvidenceCount;this.dynamicEvidenceCount=dynamicEvidenceCount;this.quantitativeCount=quantitativeCount;this.sourceLimitedCount=sourceLimitedCount;this.centerTarget=centerTarget;this.targetSpan=targetSpan;this.medianBiasCorrectionAbs=medianBiasCorrectionAbs;this.medianOvershootAbs=medianOvershootAbs;this.medianSteadyErrorAbs=medianSteadyErrorAbs;this.medianPeakDuty=medianPeakDuty;this.medianInitialIAbs=medianInitialIAbs;this.dominantBiasStatus=dominantBiasStatus==null?"":dominantBiasStatus;this.dominantPidStatus=dominantPidStatus==null?"":dominantPidStatus;}
 public static DcIacTuningSessionSummary summarize(int sequence,String config,DcIacSettingsAccess.Snapshot settings,List<DcIacStaticEvidence> statics,List<DcIacDynamicEvidence> dynamics,List<DcIacStaticRecommendation> staticRecs,List<DcIacPidRecommendation> pidRecs){List<Double>centers=new ArrayList<Double>(),bias=new ArrayList<Double>(),over=new ArrayList<Double>(),ss=new ArrayList<Double>(),peak=new ArrayList<Double>(),initialI=new ArrayList<Double>();int q=0,l=0;if(statics!=null)for(DcIacStaticEvidence r:statics)if(r.getOperatingContext()==DcIacOperatingContext.RUNNING_IDLE){add(centers,r.getTarget());add(bias,Math.abs(r.getCorrection()));}if(dynamics!=null)for(DcIacDynamicEvidence r:dynamics)if(r.getOperatingContext()==DcIacOperatingContext.RUNNING_IDLE&&r.isSafeLocalStep()){DcIacMeasurement m=r.getMeasurement();add(centers,m.getOperatingCenterTarget());add(over,Math.abs(m.getOvershootPercentOfStep()));add(ss,Math.abs(m.getSteadyStateError()));add(peak,m.getPeakAbsoluteDuty());add(initialI,Math.abs(m.getInitialITerm()));if(r.getTier()==DcIacDynamicEvidence.Tier.QUANTITATIVE)q++;if(r.getTier()==DcIacDynamicEvidence.Tier.SOURCE_LIMITED_SUPPORT)l++;}return new DcIacTuningSessionSummary(sequence,config,settings==null?Double.NaN:settings.getPFactor(),settings==null?Double.NaN:settings.getIFactor(),settings==null?Double.NaN:settings.getDFactor(),statics==null?0:statics.size(),dynamics==null?0:dynamics.size(),q,l,median(centers),range(centers),median(bias),median(over),median(ss),median(peak),median(initialI),dominantStatic(staticRecs),dominantPid(pidRecs));}
 public int getSequence(){return sequence;}public String getConfigurationName(){return configurationName;}public double getP(){return p;}public double getI(){return i;}public double getD(){return d;}public int getStaticEvidenceCount(){return staticEvidenceCount;}public int getDynamicEvidenceCount(){return dynamicEvidenceCount;}public int getQuantitativeCount(){return quantitativeCount;}public int getSourceLimitedCount(){return sourceLimitedCount;}public double getCenterTarget(){return centerTarget;}public double getTargetSpan(){return targetSpan;}public double getMedianBiasCorrectionAbs(){return medianBiasCorrectionAbs;}public double getMedianOvershootAbs(){return medianOvershootAbs;}public double getMedianSteadyErrorAbs(){return medianSteadyErrorAbs;}public double getMedianPeakDuty(){return medianPeakDuty;}public double getMedianInitialIAbs(){return medianInitialIAbs;}public String getDominantBiasStatus(){return dominantBiasStatus;}public String getDominantPidStatus(){return dominantPidStatus;}
 private static String dominantStatic(List<DcIacStaticRecommendation>rows){if(rows==null)return"NONE";String r="NONE";for(DcIacStaticRecommendation x:rows){if(x.getOperatingContext()!=DcIacOperatingContext.RUNNING_IDLE)continue;if(x.isActionableBiasChange())return x.getStatus();if(DcIacStaticRecommendation.NOT_CONVERGED.equals(x.getStatus()))r=x.getStatus();else if(DcIacStaticRecommendation.NO_CHANGE.equals(x.getStatus())&&"NONE".equals(r))r=x.getStatus();else if(DcIacStaticRecommendation.COLLECT_MORE.equals(x.getStatus())&&"NONE".equals(r))r=x.getStatus();}return r;}
 private static String dominantPid(List<DcIacPidRecommendation>rows){if(rows==null)return"NONE";String r="NONE";for(DcIacPidRecommendation x:rows){if(x.getOperatingContext()!=DcIacOperatingContext.RUNNING_IDLE)continue;if(x.isReady())return x.getStatus();if(DcIacPidRecommendation.BLOCKED_BIAS.equals(x.getStatus()))r=x.getStatus();else if(DcIacPidRecommendation.SOURCE_LIMITED.equals(x.getStatus())&&"NONE".equals(r))r=x.getStatus();else if(DcIacPidRecommendation.NO_CHANGE.equals(x.getStatus())&&"NONE".equals(r))r=x.getStatus();else if(DcIacPidRecommendation.COLLECT_MORE.equals(x.getStatus())&&"NONE".equals(r))r=x.getStatus();}return r;}
 private static void add(List<Double>v,double x){if(finite(x))v.add(Double.valueOf(x));}private static double median(List<Double>v){if(v==null||v.isEmpty())return Double.NaN;List<Double>c=new ArrayList<Double>(v);Collections.sort(c);int m=c.size()/2;return(c.size()&1)==1?c.get(m).doubleValue():(c.get(m-1).doubleValue()+c.get(m).doubleValue())*.5;}private static double range(List<Double>v){if(v==null||v.isEmpty())return Double.NaN;double lo=Double.POSITIVE_INFINITY,hi=Double.NEGATIVE_INFINITY;for(Double x:v)if(x!=null&&finite(x.doubleValue())){lo=Math.min(lo,x.doubleValue());hi=Math.max(hi,x.doubleValue());}return lo==Double.POSITIVE_INFINITY?Double.NaN:hi-lo;}private static boolean finite(double v){return!Double.isNaN(v)&&!Double.isInfinite(v);}
}
