package se.anders.tunerstudio.pidautotune.recommendation;

import se.anders.tunerstudio.pidautotune.controller.DcIacSettingsAccess;
import se.anders.tunerstudio.pidautotune.live.DcIacDynamicEvidence;
import se.anders.tunerstudio.pidautotune.live.DcIacMeasurement;
import se.anders.tunerstudio.pidautotune.live.DcIacOperatingContext;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/** Conservative local PID engine: static bias dependency, source-limit policy, one gain per iteration. */
public final class DcIacPidRecommendationEngine {
    private static final double LOCAL_CENTER_TOLERANCE=2.50,STATIC_MATCH_TOLERANCE=2.00,MAX_INITIAL_I_SPAN=2.50,HIGH_OVERSHOOT=25.0,SEVERE_OVERSHOOT=45.0,CLEAN_OVERSHOOT=10.0,HIGH_SS_ERROR=.40,SLOW_SETTLING=.25,EDGE_DUTY_CAUTION=80.0,NOMINAL_LOOP_SECONDS=.002;
    private static final int MIN_LOCAL_STEPS=4,MIN_OPENING=2,MIN_CLOSING=2,MIN_QUANTITATIVE_FOR_INCREASE=3;
    public List<DcIacPidRecommendation> evaluate(List<DcIacDynamicEvidence> evidence,List<DcIacStaticRecommendation> statics,DcIacSettingsAccess.Snapshot settings){
        List<DcIacDynamicEvidence> usable=new ArrayList<DcIacDynamicEvidence>();if(evidence!=null)for(DcIacDynamicEvidence r:evidence)if(r!=null&&r.isSafeLocalStep())usable.add(r);
        Collections.sort(usable,new Comparator<DcIacDynamicEvidence>(){public int compare(DcIacDynamicEvidence a,DcIacDynamicEvidence b){int c=a.getOperatingContext().compareTo(b.getOperatingContext());return c!=0?c:Double.compare(a.getMeasurement().getOperatingCenterTarget(),b.getMeasurement().getOperatingCenterTarget());}});
        List<Group> groups=new ArrayList<Group>();for(DcIacDynamicEvidence row:usable){Group best=null;double bd=Double.POSITIVE_INFINITY,center=row.getMeasurement().getOperatingCenterTarget();for(Group g:groups){if(g.context!=row.getOperatingContext())continue;double d=Math.abs(g.center()-center);if(d<=LOCAL_CENTER_TOLERANCE&&d<bd){best=g;bd=d;}}if(best==null){best=new Group(row.getOperatingContext());groups.add(best);}best.rows.add(row);}
        List<DcIacPidRecommendation> result=new ArrayList<DcIacPidRecommendation>();for(Group g:groups)result.add(summarize(g,statics,settings));Collections.sort(result,new Comparator<DcIacPidRecommendation>(){public int compare(DcIacPidRecommendation a,DcIacPidRecommendation b){int c=a.getOperatingContext().compareTo(b.getOperatingContext());return c!=0?c:Double.compare(a.getCenterTarget(),b.getCenterTarget());}});return result;
    }
    private static DcIacPidRecommendation summarize(Group group,List<DcIacStaticRecommendation> statics,DcIacSettingsAccess.Snapshot settings){
        double center=group.center();int quant=0,limited=0,opening=0,closing=0,reversalEvents=0;List<Double> over=new ArrayList<Double>(),qOver=new ArrayList<Double>(),ss=new ArrayList<Double>(),settle=new ArrayList<Double>(),rise=new ArrayList<Double>(),peak=new ArrayList<Double>(),initialI=new ArrayList<Double>(),edge=new ArrayList<Double>();
        for(DcIacDynamicEvidence row:group.rows){DcIacMeasurement m=row.getMeasurement();if(row.getTier()==DcIacDynamicEvidence.Tier.QUANTITATIVE)quant++;if(row.getTier()==DcIacDynamicEvidence.Tier.SOURCE_LIMITED_SUPPORT)limited++;if(row.isOpening())opening++;if(row.isClosing())closing++;add(over,Math.abs(m.getOvershootPercentOfStep()));if(row.getTier()==DcIacDynamicEvidence.Tier.QUANTITATIVE){add(qOver,Math.abs(m.getOvershootPercentOfStep()));add(settle,m.getSettlingSeconds());add(rise,m.getRiseOrFallSeconds());}add(ss,Math.abs(m.getSteadyStateError()));add(peak,m.getPeakAbsoluteDuty());add(initialI,m.getInitialITerm());add(edge,Math.abs(m.getPredictedCommandEdgeDuty()));if(m.getDutyReversals()>=2)reversalEvents++;}
        double medOver=median(over),medQOver=median(qOver),medSs=median(ss),medSettle=median(settle),medRise=median(rise),medPeak=median(peak),medInitialI=medianAbs(initialI),initialISpan=range(initialI),maxEdge=max(edge);
        double p=settings==null?Double.NaN:settings.getPFactor(),i=settings==null?Double.NaN:settings.getIFactor(),d=settings==null?Double.NaN:settings.getDFactor(),kick=finite(p)&&Math.abs(p)>1e-9&&finite(d)?Math.abs(d/NOMINAL_LOOP_SECONDS/p):Double.NaN;
        DcIacStaticRecommendation bias=nearestStatic(statics,group.context,center);String biasStatus=bias==null?"MISSING":bias.getStatus();String status,action="None",detail;double pc=0,ic=0,dc=0;
        if(group.context!=DcIacOperatingContext.RUNNING_IDLE){status=DcIacPidRecommendation.BLOCKED_CONTEXT;detail="Dynamic evidence is retained as context, but PID candidates are produced only from running-idle evidence so engine-off/other actuator load is not mixed into the idle tune.";}
        else if(bias==null||!bias.isBiasReadyForPid()){status=DcIacPidRecommendation.BLOCKED_BIAS;detail=bias!=null&&bias.isActionableBiasChange()?"Local static evidence supports a bias/feed-forward change first. Apply manually and revalidate until NO_CHANGE before gain math.":"Local static bias is not yet converged/cleared. PID stays blocked so inherited I correction is not mistaken for plant dynamics.";}
        else if(settings==null||!settings.arePidGainsKnown()){status=DcIacPidRecommendation.COLLECT_MORE;detail="Configured DC-IAC P/I/D values are unavailable.";}
        else if(group.rows.size()<MIN_LOCAL_STEPS||opening<MIN_OPENING||closing<MIN_CLOSING){status=DcIacPidRecommendation.COLLECT_MORE;detail="Collect at least four safe local steps, ideally two opening and two closing, under the same cleared-bias state.";}
        else if(finite(initialISpan)&&initialISpan>MAX_INITIAL_I_SPAN){status=DcIacPidRecommendation.INCONSISTENT;detail="Initial I state varies too much across local steps for an attributable gain candidate.";}
        else{boolean harmful=finite(medOver)&&medOver>=HIGH_OVERSHOOT,severe=finite(medOver)&&medOver>=SEVERE_OVERSHOOT,reversal=reversalEvents>=Math.max(2,group.rows.size()/2),edgeCaution=finite(maxEdge)&&maxEdge>=EDGE_DUTY_CAUTION,dKickHigh=finite(kick)&&kick>=.50&&d>0,allLimited=quant==0&&limited>0;
            if(dKickHigh&&(harmful||reversal||edgeCaution)){status=DcIacPidRecommendation.READY_PID;dc=severe||edgeCaution?-20:-15;action="Reduce D";detail="Overshoot/reversal/edge-duty evidence coincides with substantial D-on-error setpoint kick. Change D only, then repeat the same local test.";}
            else if(harmful||reversal){status=DcIacPidRecommendation.READY_PID;pc=severe?-15:-10;action="Reduce P";detail="Repeated safe local steps show enough underdamping to justify a bounded P-only reduction.";}
            else if(allLimited){status=DcIacPidRecommendation.SOURCE_LIMITED;detail="Safe local events are repeatable but source-rate limited. They can justify reductions when harm is observed, but absence of observed peaks cannot justify increasing a gain.";}
            else if(quant<MIN_QUANTITATIVE_FOR_INCREASE){status=DcIacPidRecommendation.COLLECT_MORE;detail="More source-resolved quantitative steps are required before a gain increase can be justified.";}
            else if(finite(medQOver)&&medQOver<=CLEAN_OVERSHOOT&&finite(medSettle)&&medSettle>=SLOW_SETTLING&&(!finite(maxEdge)||maxEdge<70)){status=DcIacPidRecommendation.READY_PID;pc=5;action="Increase P";detail="Resolved local responses are clean but comparatively slow with ample predicted duty headroom. A small P-only increase is proposed.";}
            else if(finite(medSs)&&medSs>=HIGH_SS_ERROR&&finite(medQOver)&&medQOver<=CLEAN_OVERSHOOT){status=DcIacPidRecommendation.READY_PID;ic=10;action="Increase I";detail="Bias is cleared and resolved responses are clean, but repeatable residual position error remains. A bounded I-only increase is proposed.";}
            else{status=DcIacPidRecommendation.NO_CHANGE;detail="Current local P/I/D behavior does not justify a bounded one-axis change under the conservative evidence rules.";}}
        double pp=apply(p,pc),pi=apply(i,ic),pd=apply(d,dc),conf=confidence(status,group.rows.size(),quant,opening,closing,medOver,initialISpan,bias);
        return new DcIacPidRecommendation(status,group.context,center,group.rows.size(),quant,limited,opening,closing,biasStatus,p,i,d,pp,pi,pd,pc,ic,dc,medOver,medSs,medSettle,medRise,medPeak,medInitialI,kick,conf,action,detail);
    }
    private static DcIacStaticRecommendation nearestStatic(List<DcIacStaticRecommendation> rows,DcIacOperatingContext context,double target){DcIacStaticRecommendation best=null;double bd=Double.POSITIVE_INFINITY;if(rows==null)return null;for(DcIacStaticRecommendation r:rows){if(r.getOperatingContext()!=context)continue;double d=Math.abs(r.getCenterTarget()-target);if(d<=STATIC_MATCH_TOLERANCE&&d<bd){best=r;bd=d;}}return best;}
    private static double confidence(String status,int count,int quant,int open,int close,double over,double iSpan,DcIacStaticRecommendation bias){double v=45+Math.min(24,Math.max(0,count-3)*6)+Math.min(18,quant*4);if(open>=2&&close>=2)v+=8;if(bias!=null&&bias.isBiasReadyForPid())v+=Math.min(8,bias.getConfidencePercent()/20);if(finite(iSpan))v-=Math.min(12,iSpan/MAX_INITIAL_I_SPAN*8);if(DcIacPidRecommendation.BLOCKED_BIAS.equals(status)||DcIacPidRecommendation.BLOCKED_CONTEXT.equals(status)||DcIacPidRecommendation.COLLECT_MORE.equals(status)||DcIacPidRecommendation.SOURCE_LIMITED.equals(status))v=Math.min(v,49);if(DcIacPidRecommendation.INCONSISTENT.equals(status))v=Math.min(v,35);if(finite(over)&&over>=SEVERE_OVERSHOOT&&DcIacPidRecommendation.READY_PID.equals(status))v+=5;return clamp(v,0,95);}
    private static double apply(double v,double pct){return finite(v)?v*(1+pct/100):Double.NaN;}private static void add(List<Double>v,double x){if(finite(x))v.add(Double.valueOf(x));}
    private static double median(List<Double>v){if(v==null||v.isEmpty())return Double.NaN;List<Double>c=new ArrayList<Double>(v);Collections.sort(c);int m=c.size()/2;return(c.size()&1)==1?c.get(m).doubleValue():(c.get(m-1).doubleValue()+c.get(m).doubleValue())*.5;}
    private static double medianAbs(List<Double>v){List<Double>a=new ArrayList<Double>();if(v!=null)for(Double x:v)if(x!=null&&finite(x.doubleValue()))a.add(Double.valueOf(Math.abs(x.doubleValue())));return median(a);}private static double range(List<Double>v){if(v==null||v.isEmpty())return Double.NaN;double lo=Double.POSITIVE_INFINITY,hi=Double.NEGATIVE_INFINITY;int n=0;for(Double x:v)if(x!=null&&finite(x.doubleValue())){lo=Math.min(lo,x.doubleValue());hi=Math.max(hi,x.doubleValue());n++;}return n==0?Double.NaN:hi-lo;}private static double max(List<Double>v){double r=Double.NaN;if(v!=null)for(Double x:v)if(x!=null&&finite(x.doubleValue())&&(!finite(r)||x.doubleValue()>r))r=x.doubleValue();return r;}private static double clamp(double v,double lo,double hi){return Math.max(lo,Math.min(hi,v));}private static boolean finite(double v){return!Double.isNaN(v)&&!Double.isInfinite(v);}
    private static final class Group{private final DcIacOperatingContext context;private final List<DcIacDynamicEvidence> rows=new ArrayList<DcIacDynamicEvidence>();private Group(DcIacOperatingContext c){context=c==null?DcIacOperatingContext.UNKNOWN:c;}private double center(){double s=0;int n=0;for(DcIacDynamicEvidence r:rows){double v=r.getMeasurement().getOperatingCenterTarget();if(finite(v)){s+=v;n++;}}return n==0?Double.NaN:s/n;}}
}
