package se.anders.tunerstudio.pidautotune.recommendation;
import se.anders.tunerstudio.pidautotune.live.DcIacOperatingContext;
/** Read-only local DC-IAC PID candidate derived from already-qualified dynamic evidence. */
public final class DcIacPidRecommendation {
 public static final String BLOCKED_BIAS="BLOCKED_BIAS",BLOCKED_CONTEXT="BLOCKED_CONTEXT",COLLECT_MORE="COLLECT_MORE",SOURCE_LIMITED="SOURCE_LIMITED",INCONSISTENT="INCONSISTENT",NO_CHANGE="NO_CHANGE",READY_PID="READY_PID";
 private final String status,biasStatus,primaryAction,detail;private final DcIacOperatingContext context;private final double center,currentP,currentI,currentD,proposedP,proposedI,proposedD,pChange,iChange,dChange,overshoot,ss,settling,rise,peak,initialI,kickRatio,confidence;private final int count,quant,limited,opening,closing;
 public DcIacPidRecommendation(String status,DcIacOperatingContext context,double center,int count,int quant,int limited,int opening,int closing,String biasStatus,double currentP,double currentI,double currentD,double proposedP,double proposedI,double proposedD,double pChange,double iChange,double dChange,double overshoot,double ss,double settling,double rise,double peak,double initialI,double kickRatio,double confidence,String primaryAction,String detail){this.status=status==null?"":status;this.context=context==null?DcIacOperatingContext.UNKNOWN:context;this.center=center;this.count=count;this.quant=quant;this.limited=limited;this.opening=opening;this.closing=closing;this.biasStatus=biasStatus==null?"":biasStatus;this.currentP=currentP;this.currentI=currentI;this.currentD=currentD;this.proposedP=proposedP;this.proposedI=proposedI;this.proposedD=proposedD;this.pChange=pChange;this.iChange=iChange;this.dChange=dChange;this.overshoot=overshoot;this.ss=ss;this.settling=settling;this.rise=rise;this.peak=peak;this.initialI=initialI;this.kickRatio=kickRatio;this.confidence=confidence;this.primaryAction=primaryAction==null?"":primaryAction;this.detail=detail==null?"":detail;}
 public String getStatus(){return status;}public DcIacOperatingContext getOperatingContext(){return context;}public double getCenterTarget(){return center;}public int getEvidenceCount(){return count;}public int getQuantitativeCount(){return quant;}public int getSourceLimitedCount(){return limited;}public int getOpeningCount(){return opening;}public int getClosingCount(){return closing;}public String getBiasStatus(){return biasStatus;}public double getCurrentP(){return currentP;}public double getCurrentI(){return currentI;}public double getCurrentD(){return currentD;}public double getProposedP(){return proposedP;}public double getProposedI(){return proposedI;}public double getProposedD(){return proposedD;}public double getPChangePercent(){return pChange;}public double getIChangePercent(){return iChange;}public double getDChangePercent(){return dChange;}public double getMedianOvershootPercent(){return overshoot;}public double getMedianSteadyErrorAbs(){return ss;}public double getMedianSettlingSeconds(){return settling;}public double getMedianRiseSeconds(){return rise;}public double getMedianPeakDuty(){return peak;}public double getMedianInitialIAbs(){return initialI;}public double getDerivativeKickRatio(){return kickRatio;}public double getConfidencePercent(){return confidence;}public String getPrimaryAction(){return primaryAction;}public String getDetail(){return detail;}public boolean isReady(){return READY_PID.equals(status);}
}
